### ISSUE TITLE
Extra stuff being output

### ISSUE THREAD

**Issue by vasuvasu** [michael-misshore/loadcss-rails#1]
Noticing some stuff getting output in the rendered HTML. Looks like some quotes are rendering out, and a `<script>` tag with loadCSS (might be normal/expected) .. picture might explain it better. This is resulting in some white space at the top of the document. Oh and most importantly, it's being output in `<body>` instead of `<head>`

![screen shot 2015-09-10 at 4 35 32 pm](https://cloud.githubusercontent.com/assets/2042056/9801700/4bf88d06-57da-11e5-833f-f7ad392ab1cb.png)

**Comment by michael-misshore** [comment]
IIRC, we talked about this and determined it's a non-issue. I'm closing this for now but let me know if this is indeed still an issue.
